config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'device_setting' => 'mfa#index'
  get 'mfa_auth' => 'mfa#new'
  post 'mfa_auth' => 'mfa#create'

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mfa_controller.rb
class MfaController < ApplicationController
  def index
    unless user = User.find_by(id: session[:before_mfa_user_id])
      return redirect_to login_url
    end

    # if user.otp_secret_key.present?
    #   user.otp_secret_key
    #   return render "new"
    # end

    # 認証デバイス登録
    unless user.otp_secret_key.present?
      secret = ROTP::Base32.random
      user.update(otp_secret_key: secret)
    end

    totp = ROTP::TOTP.new(user.otp_secret_key, issuer: "two-factor_sample")
    uri = totp.provisioning_uri("hailong@test.jp")
    @qr = RQRCode::QRCode.new(uri, level: :h)
  end

  def new
  end

  def create
    if user = User.find_by(id: session[:before_mfa_user_id])
      totp = ROTP::TOTP.new(user.otp_secret_key, issuer: "two-factor_sample")
      if totp.verify(params[:otp_code])
        log_in user
        return redirect_to root_url, notice: "認証成功しました!"
      else
        flash.now[:alert] = "認証コードは無効です。"
        return render "new"
      end
    else
      return redirect_to root_url, notice: "ログイン失敗しました!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      session[:before_mfa_user_id] = user.id
      # log_in user
      # redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email is invalid"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :otp_secret_key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mfa_helper.rb
module MfaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id:user_id)
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<% if logged_in? %>
  Logged in as <%= current_user.email %>.
  <%= link_to "ログアウト", logout_path %>
<% else %>
  <p> ログインまたはユーザ登録してください。</p>
  <div>
  <%= link_to "ログイン", login_path %>
  </div>
  <div>
  <%= link_to "新規ユーザ登録", signup_path %>
  </div>
<% end %>

<p id=”notice”><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwoFactorAuthentication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mfa/create.html.erb
<h1>Mfa#create</h1>
<p>Find me in app/views/mfa/create.html.erb</p>

app/views/mfa/index.html.erb
<h1>認証デバイス登録</h1>
<p>下記のQRコードをスキャン後にコード認証を行ってください。</p>

<div class="qrcode">
  <%= raw @qr.as_html %>
</div>

<div>
<%= link_to "コード認証をする", mfa_auth_url %>
</div>

app/views/mfa/new.html.erb
<p id="alert"><%= alert %></p>

<h1>コード入力</h1>

<%= form_tag mfa_auth_path do |form| %>
  <div class="field'>
    <%= label_tag :認証コード %>
    <%= text_field_tag :otp_code %>
  </div>
  <br>
  <div class="actions">
    <%= submit_tag "検証" %>
  </div>

  <br>
  <div>
    <%= link_to "ログイン画面に戻る", login_url %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :otp_secret_key %>
    <%= form.text_field :otp_secret_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Otp secret key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.otp_secret_key %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Otp secret key:</strong>
  <%= @user.otp_secret_key %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>